### PR TITLE
[am] Introduce new edge state "waiting" represented by blue.

### PR DESCRIPTION
**Pull request by JDevlieghere**

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@JDevlieghere `get_zippered_state` isn't defined?

**Comment by JDevlieghere** [comment]
> @JDevlieghere `get_zippered_state` isn't defined?

Looks like I messed up creating the separate PRs.

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Pull request merged**
