### PR TITLE
[test] Temporarily disable repeat-root-2.test

### PR DESCRIPTION
**Pull request by JDevlieghere**
This is failing during PR testing.

rdar://problem/57991261

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
Note that this is caused by some sort of race condition in the testing environment.  I doubt repeat-root-2 is the only place this hits, so I'm not sure merging this will solve anything in practice.

I believe this would be properly addressed by the combination of:
https://github.com/apple/apple-llvm-infrastructure-tools/pull/68
and
https://github.com/bogner/apple-llvm-infrastructure-tools/pull/1

**Comment by dexonsmith** [comment]
> Note that this is caused by some sort of race condition in the testing environment. I doubt repeat-root-2 is the only place this hits, so I'm not sure merging this will solve anything in practice.
> 
> I believe this would be properly addressed by the combination of:
> #68
> and
> [bogner#1](https://github.com/bogner/apple-llvm-infrastructure-tools/pull/1)

Specifically, this change:
https://github.com/bogner/apple-llvm-infrastructure-tools/pull/1/commits/300f80df3ce3b20c709416393e4634430486fd0c

**Pull request merged**
