### PR TITLE
am: add support for detecting if a secondary edge commit is blocked by the unmerged primary edge

### PR DESCRIPTION
**Pull request by hyp**

### CODE REVIEW

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@shahmishal I can't trigger testing .

**Comment by shahmishal** [comment]
We had network outage, it will recover soon.

**Comment by hyp** [comment]
@swift-ci test

**Pull request merged**
