### PR TITLE
[am] Remove is_secondary_edge_commit_blocked_by_primary_edge

### PR DESCRIPTION
**Pull request by JDevlieghere**
Remove the method is_secondary_edge_commit_blocked_by_primary_edge and
replace the functionality with trying to do the merge locally.

### CODE REVIEW

**Comment by hyp** [comment]
@JDevlieghere looks like you have multiple things in this PR. is this intentional?

**Comment by JDevlieghere** [comment]
They're all related to this change, but I'll split them up into separate PRs to make it easier to review.

**Comment by hyp** [comment]
@JDevliegher

**Comment by hyp** [comment]
Oops, sorry. Re-opening.

**Comment by hyp** [comment]
That should work for conflict detection, but now there's a conflict in this PR as I changes some status code. Please update.

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Pull request merged**
