### PR TITLE
Upgrade pip before installing the packages

### PR DESCRIPTION
**Pull request by azharudd**

### CODE REVIEW

**Review by edymtt — APPROVED** [review]

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Pull request merged**
