### PR TITLE
[am] Update graph after branch renaming

### PR DESCRIPTION
**Pull request by azharudd**

### CODE REVIEW

**Review by hyp — APPROVED** [review]
LGTM

**Review by JDevlieghere — APPROVED** [review]

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
These failures have nothing to do with this PR.

**Comment by azharudd** [comment]
Fixing the errors reported. They are not related to this PR.

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
Merging.

**Pull request merged**
