### PR TITLE
[am] Add 'graph' tool that prints the automerger graph using graphviz.

### PR DESCRIPTION
**Pull request by JDevlieghere**
This adds the 'graph' sub-command to the am tool to generate and display
the automerger graph using graphviz.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
CC @hyp @dexonsmith

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by JDevlieghere** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci test

**Comment by hyp** [comment]
@swift-ci clean test

**Comment by hyp** [comment]
@swift-ci clean test

**Comment by hyp** [comment]
@swift-ci clean test

**Comment by hyp** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
Looking into this issue, please hold off from triggering new runs.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
@swift-ci test

**Pull request merged**
