### PR TITLE
[am] Update graph after branch merging and renaming

### PR DESCRIPTION
**Pull request by azharudd**

### CODE REVIEW

**Comment by azharudd** [comment]
@swift-ci please test

**Review by hyp — APPROVED** [review]
LGTM!

**Comment by azharudd** [comment]
@swift-ci please test

**Review by JDevlieghere — APPROVED** [review]
Thank you!

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
Finally able to get the PR test build to pass, and not abort or fail due to some unrelated error.

**Pull request merged**
