### PR TITLE
am: Make the subgraph titles clear in the graph

### PR DESCRIPTION
**Pull request by dexonsmith**

### CODE REVIEW

**Comment by dexonsmith** [comment]
@swift-ci test

**Comment by dexonsmith** [comment]
@swift-ci test

**Comment by dexonsmith** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
Looks like a CI problem:
```
14:58:35 ==================================== ERRORS ====================================
14:58:35 _________ ERROR collecting test/auto-updater/test_check_for_updates.py _________
14:58:35 ImportError while importing test module '/Users/buildnode/jenkins/workspace/llvm-infrastructure-tools-pr-macOS/apple-llvm-infrastructure-tool/test/auto-updater/test_check_for_updates.py'.
14:58:35 Hint: make sure your test modules/packages have valid Python names.
14:58:35 Traceback:
14:58:35 auto-updater/test_check_for_updates.py:9: in <module>
14:58:35     from git import Repo
14:58:35 .python_env/lib/python3.7/site-packages/git/__init__.py:38: in <module>
14:58:35     from git.exc import *                       # @NoMove @IgnorePep8
14:58:35 .python_env/lib/python3.7/site-packages/git/exc.py:9: in <module>
14:58:35     from git.compat import UnicodeMixin, safe_decode, string_types
14:58:35 .python_env/lib/python3.7/site-packages/git/compat.py:16: in <module>
14:58:35     from gitdb.utils.compat import (
14:58:35 E   ModuleNotFoundError: No module named 'gitdb.utils.compat'
14:58:35 !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by dexonsmith** [comment]
@swift-ci please test again

**Comment by dexonsmith** [comment]
@swift-ci please test

**Comment by dexonsmith** [comment]
@shahmishal @hyp, I hit the same problem the second run.  Any idea what's going on?  (Also, tests do pass locally, so if you have access to the "merge pull request" button feel free to do so.)

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by dexonsmith** [comment]
@swift-ci please test again

**Comment by dexonsmith** [comment]
@swift-ci please test

**Comment by azharudd** [comment]
@swift-ci please test

**Pull request merged**
