### PR TITLE
[gitignore] Ignore distribution and mypy files

### PR DESCRIPTION
**Pull request by JDevlieghere**
This ignores files created while running the test suite.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by dexonsmith** [comment]
Can we update the test suite so that it generates files in a smaller number of directories?

**Comment by JDevlieghere** [comment]
We could be more specific and only ignore `git_apple_llvm.egg-info/` and `test/.mypy_cache`, but it seemed more future proof to go ahead and ignore all files belonging to those components. I'm not sure what these directories look like on different platforms.  

Personally I'd take it even further and just use [Github's default .gitignore for Python](https://github.com/github/gitignore/blob/master/Python.gitignore) which includes everything ignored here.

**Comment by hyp** [comment]
> We could be more specific and only ignore `git_apple_llvm.egg-info/` and `test/.mypy_cache`, but it seemed more future proof to go ahead and ignore all files belonging to those components. I'm not sure what these directories look like on different platforms.
> 
> Personally I'd take it even further and just use [Github's default .gitignore for Python](https://github.com/github/gitignore/blob/master/Python.gitignore) which includes everything ignored here.

Yes, that's a good idea.

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Comment by JDevlieghere** [comment]
@swift-ci test

**Pull request merged**
