### PR TITLE
Initial implementation of the "git apple-llvm pr" tool with "list" and "test" support

### PR DESCRIPTION
**Pull request by hyp**
@cmatthew @azharudd I started working on the pr list command support for GitHub.

### CODE REVIEW

**Comment by hyp** [comment]
testing pr commenting

**Comment by hyp** [comment]
testing 2

**Comment by hyp** [comment]
swift-ci please test

**Comment by hyp** [comment]
swift-ci please test

**Comment by hyp** [comment]
swift-ci please test

**Comment by hyp** [comment]
@swift-ci please test

**Comment by hyp** [comment]
I added initial support for `test` command which triggers swift-ci on GitHub . This works for this repo :)

**Comment by hyp** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by hyp** [comment]
Merged in #17

**Pull request closed without merging**
